In [1]:
import os
os.chdir(r'E:\R1j1s5k1r1n\Udemy\Python\Practice')

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
 
 

In [3]:
df = pd.read_csv("all_csv sorted.csv",index_col = 'Unnamed: 0')
df.head()

Country code     Country  Continental region  NO. OF Internet Plans   \
0           IL      Israel           NEAR EAST                    27.0   
1           KG  Kyrgyzstan   CIS (FORMER USSR)                    20.0   
2           FJ        Fiji             OCEANIA                    18.0   
3           IT       Italy      WESTERN EUROPE                    29.0   
4           SD       Sudan  SUB-SAHARAN AFRICA                    33.0   

  Average price of 1GB (USD)  Cheapest 1GB for 30 days (USD)  \
0                       0.05                            0.02   
1                       0.15                            0.10   
2                       0.19                            0.05   
3                       0.27                            0.09   
4                       0.27                            0.03   

   Most expensive 1GB (USD) Average price of 1GB (USD  at the start of 2021)  \
0                     20.95                                             0.11   
1                      7.08                                             0.21   
2                      0.85                                             0.59   
3                      3.54                                             0.43   
4                      0.92                                             0.63   

  Average price of 1GB (USD – at start of 2020) Internet users  Population  \
0                                          0.90      6,788,737   8,381,516   
1                                          0.27      2,309,235   6,304,030   
2                                          3.57        452,479     883,483   
3                                          1.73     50,540,000  60,627,291   
4                                          0.68     12,512,639  41,801,533   

   Avg \n(Mbit/s)Ookla  
0                28.01  
1                16.30  
2                25.99  
3                37.15  
4                 9.50

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 243 entries, 0 to 243
Data columns (total 12 columns):
 #   Column                                            Non-Null Count  Dtype  
---  ------                                            --------------  -----  
 0   Country code                                      243 non-null    object 
 1   Country                                           243 non-null    object 
 2   Continental region                                243 non-null    object 
 3   NO. OF Internet Plans                             231 non-null    float64
 4   Average price of 1GB (USD)                        243 non-null    object 
 5   Cheapest 1GB for 30 days (USD)                    231 non-null    float64
 6   Most expensive 1GB (USD)                          231 non-null    float64
 7   Average price of 1GB (USD  at the start of 2021)  231 non-null    object 
 8   Average price of 1GB (USD – at start of 2020)     231 non-null    object 
 9   Internet users       

In [5]:
df.isna().sum()

Country code                                          0
Country                                               0
Continental region                                    0
NO. OF Internet Plans                                12
Average price of 1GB (USD)                            0
Cheapest 1GB for 30 days (USD)                       12
Most expensive 1GB (USD)                             12
Average price of 1GB (USD  at the start of 2021)     12
Average price of 1GB (USD – at start of 2020)        12
Internet users                                       30
Population                                           32
Avg \n(Mbit/s)Ookla                                 102
dtype: int64

In [6]:
df.columns

Index(['Country code', 'Country', 'Continental region',
       'NO. OF Internet Plans ', 'Average price of 1GB (USD)',
       'Cheapest 1GB for 30 days (USD)', 'Most expensive 1GB (USD)',
       'Average price of 1GB (USD  at the start of 2021)',
       'Average price of 1GB (USD – at start of 2020)', 'Internet users',
       'Population', 'Avg \n(Mbit/s)Ookla'],
      dtype='object')

In [7]:
No_of_int_plan = df['NO. OF Internet Plans '].mean()

In [8]:
df['NO. OF Internet Plans '].fillna(No_of_int_plan, inplace = True)

In [9]:
df['NO. OF Internet Plans '].isna().sum()

0

In [10]:
columns = ['Cheapest 1GB for 30 days (USD)','Most expensive 1GB (USD)', 'Average price of 1GB (USD  at the start of 2021)','Average price of 1GB (USD – at start of 2020)'
           , 'Internet users', 'Population' , 'Avg \n(Mbit/s)Ookla'
          ]
columns

['Cheapest 1GB for 30 days (USD)',
 'Most expensive 1GB (USD)',
 'Average price of 1GB (USD  at the start of 2021)',
 'Average price of 1GB (USD – at start of 2020)',
 'Internet users',
 'Population',
 'Avg \n(Mbit/s)Ookla']

In [11]:
df[columns].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 243 entries, 0 to 243
Data columns (total 7 columns):
 #   Column                                            Non-Null Count  Dtype  
---  ------                                            --------------  -----  
 0   Cheapest 1GB for 30 days (USD)                    231 non-null    float64
 1   Most expensive 1GB (USD)                          231 non-null    float64
 2   Average price of 1GB (USD  at the start of 2021)  231 non-null    object 
 3   Average price of 1GB (USD – at start of 2020)     231 non-null    object 
 4   Internet users                                    213 non-null    object 
 5   Population                                        211 non-null    object 
 6   Avg 
(Mbit/s)Ookla                                141 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.2+ KB


In [12]:

df['Average price of 1GB (USD  at the start of 2021)'] = pd.to_numeric(df['Average price of 1GB (USD  at the start of 2021)'],errors = 'coerce')
df['Average price of 1GB (USD – at start of 2020)'] = pd.to_numeric(df['Average price of 1GB (USD – at start of 2020)'],errors = 'coerce')

In [13]:
df[columns].isna().sum()

Cheapest 1GB for 30 days (USD)                       12
Most expensive 1GB (USD)                             12
Average price of 1GB (USD  at the start of 2021)     14
Average price of 1GB (USD – at start of 2020)        15
Internet users                                       30
Population                                           32
Avg \n(Mbit/s)Ookla                                 102
dtype: int64

In [18]:
df['Internet users'] = df['Internet users'].str.replace(',', '').astype(float)

In [20]:
df['Population'] = df['Population'].str.replace(',', '').astype(float)

dtype('float64')

In [21]:
for i in columns:
    mean = df[i].mean()
    print(i, mean)

Cheapest 1GB for 30 days (USD) 1.7184415584415575
Most expensive 1GB (USD) 29.664848484848466
Average price of 1GB (USD  at the start of 2021) 5.104890829694323
Average price of 1GB (USD – at start of 2020) 8.142763157894736
Internet users 23334824.755868543
Population 36067169.208530806
Avg 
(Mbit/s)Ookla 37.27567375886524


In [22]:
df['Cheapest 1GB for 30 days (USD)'].fillna(1.7184415584415575, inplace = True)
df['Cheapest 1GB for 30 days (USD)'].unique()

array([2.00000000e-02, 1.00000000e-01, 5.00000000e-02, 9.00000000e-02,
       3.00000000e-02, 1.30000000e-01, 7.00000000e-02, 1.10000000e-01,
       0.00000000e+00, 2.40000000e-01, 1.70000000e-01, 1.60000000e-01,
       3.00000000e-01, 1.90000000e-01, 6.00000000e-02, 2.50000000e-01,
       1.00000000e-02, 1.80000000e-01, 2.20000000e-01, 1.40000000e-01,
       2.80000000e-01, 4.00000000e-02, 3.30000000e-01, 2.70000000e-01,
       4.40000000e-01, 1.20000000e-01, 4.90000000e-01, 6.00000000e-01,
       4.80000000e-01, 2.60000000e-01, 3.80000000e-01, 6.30000000e-01,
       3.40000000e-01, 8.40000000e-01, 4.70000000e-01, 6.80000000e-01,
       8.50000000e-01, 5.70000000e-01, 3.50000000e-01, 1.09000000e+00,
       5.40000000e-01, 5.00000000e-01, 2.00000000e-01, 4.50000000e-01,
       6.90000000e-01, 8.20000000e-01, 1.03000000e+00, 1.00000000e+00,
       8.30000000e-01, 4.60000000e-01, 1.41000000e+00, 1.11000000e+00,
       9.50000000e-01, 4.20000000e-01, 2.10000000e-01, 9.90000000e-01,
      

In [23]:
df['Cheapest 1GB for 30 days (USD)'].isna().sum()

0

In [24]:
df['Most expensive 1GB (USD)'].fillna(29.664848484848466, inplace = True)
df['Most expensive 1GB (USD)'].unique()

array([2.09500000e+01, 7.08000000e+00, 8.50000000e-01, 3.54000000e+00,
       9.20000000e-01, 1.86000000e+00, 2.79000000e+00, 2.22000000e+00,
       5.53000000e+00, 1.83000000e+00, 1.18200000e+02, 2.94000000e+00,
       1.66200000e+01, 6.30000000e-01, 5.55000000e+00, 2.24000000e+00,
       1.21000000e+00, 6.86000000e+00, 8.59000000e+00, 2.35000000e+00,
       2.37500000e+01, 6.67000000e+00, 3.70000000e+00, 2.66000000e+00,
       2.26000000e+00, 2.30200000e+01, 3.47000000e+00, 2.73000000e+00,
       7.62000000e+00, 3.58800000e+01, 4.31000000e+00, 6.49000000e+00,
       1.30200000e+01, 1.41500000e+01, 2.23000000e+00, 6.29000000e+00,
       6.80000000e+00, 2.00000000e+00, 1.06000000e+00, 1.90000000e+00,
       5.25000000e+00, 5.50000000e+00, 7.26000000e+00, 3.55000000e+00,
       7.22000000e+00, 2.72000000e+00, 6.02000000e+00, 2.82000000e+00,
       9.60000000e+00, 1.63000000e+00, 2.12000000e+00, 2.38000000e+00,
       3.00000000e+00, 1.03200000e+01, 2.37000000e+00, 3.63000000e+00,
      

In [25]:
df['Average price of 1GB (USD  at the start of 2021)'].fillna(5.104890829694323, inplace = True)
df['Average price of 1GB (USD  at the start of 2021)'].unique()

array([ 0.11      ,  0.21      ,  0.59      ,  0.43      ,  0.63      ,
        0.52      ,  1.12      ,  0.7       ,  0.51      ,  0.71      ,
        0.81      ,  0.64      ,  0.89      ,  1.16      ,  0.57      ,
        0.65      ,  0.61      , 10.86      ,  0.69      ,  0.46      ,
        1.34      ,  0.5       ,  0.74      ,  0.86      ,  0.72      ,
        0.94      ,  0.09      ,  0.68      ,  4.73      ,  0.73      ,
        2.48      ,  1.05      ,  0.78      ,  0.8       ,  0.77      ,
        1.08      ,  1.5       ,  2.74      ,  1.39      ,  0.99      ,
        2.42      ,  2.75      ,  1.01      ,  3.3       ,  1.71      ,
        1.75      ,  2.14      ,  1.55      ,  1.09      ,  3.24      ,
        1.23      ,  0.98      ,  1.37      ,  2.47      ,  1.36      ,
        4.2       ,  2.13      ,  1.03      ,  1.46      ,  1.81      ,
        1.48      ,  3.41      ,  1.6       ,  1.45      ,  1.85      ,
        1.27      ,  2.07      ,  1.24      ,  2.12      ,  1.58

In [26]:
df['Average price of 1GB (USD – at start of 2020)'].fillna(8.142763157894736, inplace = True)
df['Average price of 1GB (USD – at start of 2020)'].unique()

array([ 0.9       ,  0.27      ,  3.57      ,  1.73      ,  0.68      ,
        0.91      ,  2.82      ,  0.99      ,  0.78      ,  1.87      ,
        1.21      ,  2.99      ,  2.36      ,  6.86      ,  1.31      ,
        5.15      ,  9.89      , 30.09      ,  1.85      ,  0.49      ,
        3.27      ,  6.19      ,  0.82      ,  2.25      ,  1.32      ,
        1.56      ,  0.26      ,  2.47      ,  4.87      ,  5.93      ,
        3.71      ,  0.51      ,  1.65      ,  2.51      ,  0.87      ,
        1.36      ,  2.01      ,  2.22      , 10.18      ,  1.49      ,
        1.25      ,  7.91      ,  1.18      ,  1.66      ,  6.06      ,
        1.71      ,  3.5       ,  3.28      , 65.83      ,  3.62      ,
        1.16      ,  1.6       ,  6.93      ,  2.78      ,  3.67      ,
        2.87      , 37.92      ,  8.        ,  2.48      ,  1.88      ,
        1.89      ,  3.78      ,  0.56      ,  3.79      ,  2.92      ,
       25.52      ,  4.83      ,  3.82      ,  4.55      ,  2.06

In [27]:
df['Internet users'].fillna(23334824.755868543, inplace = True)
df['Internet users'].unique()

array([6.78873700e+06, 2.30923500e+06, 4.52479000e+05, 5.05400000e+07,
       1.25126390e+07, 1.24000000e+08, 3.08378300e+06, 1.29180000e+08,
       7.12111600e+06, 1.48644560e+07, 5.94700000e+07, 1.96000000e+08,
       7.04823100e+06, 2.01000000e+04, 6.81721340e+07, 2.63500000e+07,
       1.01074000e+09, 6.60230000e+04, 1.18800000e+08, 1.39136990e+07,
       1.66924560e+07, 2.94851000e+05, 7.29236000e+05, 1.61900000e+07,
       6.99459050e+07, 3.46978480e+07, 1.50655410e+07, 8.33710000e+08,
       2.11595150e+07, 1.38711600e+06, 3.11000000e+07, 3.00000000e+07,
       7.02911000e+05, 2.33348248e+07, 2.04311000e+06, 1.63741030e+07,
       5.40727800e+06, 4.05379700e+06, 5.44182700e+06, 3.88541000e+05,
       1.35398600e+06, 1.36203231e+08, 2.20727650e+07, 2.53436850e+07,
       5.58046500e+06, 1.60010801e+08, 4.69810800e+06, 1.73221800e+06,
       1.58965900e+06, 4.83117000e+06, 4.06819400e+06, 5.47401410e+07,
       9.52105600e+06, 5.40431080e+07, 3.75530000e+04, 6.40033000e+06,
      

In [28]:
df['Population'].fillna(36067169.208530806, inplace = True)
df['Population'].unique()

array([8.38151600e+06, 6.30403000e+06, 8.83483000e+05, 6.06272910e+07,
       4.18015330e+07, 1.45734038e+08, 4.05194400e+06, 1.66303498e+08,
       2.12287630e+07, 1.87291600e+07, 6.49905110e+07, 2.67670543e+08,
       9.45261700e+06, 3.37850000e+04, 9.55459620e+07, 4.22284080e+07,
       1.42764779e+09, 1.96129000e+05, 2.13756286e+08, 1.83196180e+07,
       3.24762440e+07, 1.50082260e+07, 3.17021600e+06, 2.80957140e+07,
       8.23400880e+07, 3.79215920e+07, 2.97671020e+07, 1.35264228e+09,
       2.48981520e+07, 6.67855900e+06, 4.42461560e+07, 5.63134380e+07,
       1.26718500e+06, 3.60671692e+07, 2.95174500e+06, 5.37083200e+07,
       5.75212600e+06, 4.13731200e+06, 1.62497920e+07, 7.54388000e+05,
       1.11231780e+07, 1.95874685e+08, 3.60290930e+07, 3.15280330e+07,
       2.52162670e+07, 2.09469323e+08, 1.58543230e+07, 6.46550100e+06,
       2.08295700e+06, 5.52257600e+06, 3.71719210e+07, 9.84235980e+07,
       1.70843580e+07, 6.94284530e+07, 3.86820000e+04, 1.15652010e+07,
      

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 243 entries, 0 to 243
Data columns (total 12 columns):
 #   Column                                            Non-Null Count  Dtype  
---  ------                                            --------------  -----  
 0   Country code                                      243 non-null    object 
 1   Country                                           243 non-null    object 
 2   Continental region                                243 non-null    object 
 3   NO. OF Internet Plans                             243 non-null    float64
 4   Average price of 1GB (USD)                        243 non-null    object 
 5   Cheapest 1GB for 30 days (USD)                    243 non-null    float64
 6   Most expensive 1GB (USD)                          243 non-null    float64
 7   Average price of 1GB (USD  at the start of 2021)  243 non-null    float64
 8   Average price of 1GB (USD – at start of 2020)     243 non-null    float64
 9   Internet users       

In [30]:
df.to_csv('cleaned data.csv')